# Generated by Django 5.1.7 on 2025-03-15 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoBlock',
            fields=[
                ('info_id', models.AutoField(primary_key=True, serialize=False)),
                ('info_type', models.CharField(choices=[('id_short', 'ID Short'), ('address_info', 'Address Info'), ('notes', 'Notes')], max_length=20)),
                ('order_id', models.IntegerField(help_text='Order of this block within the form')),
            ],
            options={
                'ordering': ['order_id'],
            },
        ),
        migrations.CreateModel(
            name='FormComposition',
            fields=[
                ('form_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('has_id_short', models.BooleanField(default=False)),
                ('has_address_info', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('form_id', 'owner')},
            },
        ),
        migrations.CreateModel(
            name='AddressInfo',
            fields=[
                ('info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='address_info', serialize=False, to='api.infoblock')),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IdShort',
            fields=[
                ('info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='id_short', serialize=False, to='api.infoblock')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('number', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='notes', serialize=False, to='api.infoblock')),
                ('content', models.TextField(help_text='Maximum 1000 characters for notes', max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='infoblock',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_blocks', to='api.formcomposition'),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField(unique=True)),
                ('date_moved_in', models.DateField(blank=True, null=True)),
                ('date_moved_out', models.DateField(blank=True, null=True)),
                ('address_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='api.addressinfo')),
            ],
        ),
    ]
