# Generated by Django 5.1.7 on 2025-03-15 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_client_filledform_filledformfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filledform',
            name='client',
        ),
        migrations.RemoveField(
            model_name='filledform',
            name='form',
        ),
        migrations.RemoveField(
            model_name='filledformfield',
            name='filled_form',
        ),
        migrations.RemoveField(
            model_name='filledformfield',
            name='field',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='FilledForm',
        ),
        migrations.DeleteModel(
            name='FilledFormField',
        ),
    ]
